# https://docs.travis-ci.com/user/languages/objective-c/
# https://www.objc.io/issues/6-build-tools/travis-ci/
# https://github.com/Hearst-DD/ObjectMapper/blob/master/.travis.yml

language: objective-c
os: osx
cache: cocoapods
osx_image: xcode9.0

xcode_workspace: Demo/ZDToolKitDemo.workspace 
xcode_scheme: ZDToolKitDemo
podfile: Demo/Podfile

env:
 global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_WORKSPACE="Demo/ZDToolKitDemo.xcworkspace"
    - IOS_SCHEME="ZDToolKitDemo"
    - IOS_SDK=iphonesimulator11.0
 matrix:
    - DESTINATION="OS=11.0,name=iPhone 5s"           SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="NO"
    - DESTINATION="OS=11.0,name=iPhone 6"            SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="NO"
    - DESTINATION="OS=11.0,name=iPhone 6 Plus"       SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="NO"
    - DESTINATION="OS=11.0,name=iPhone 6s"           SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="NO"
    - DESTINATION="OS=11.0,name=iPhone 6s Plus"      SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="NO"
    - DESTINATION="OS=11.0,name=iPhone X"            SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="NO"
 
branches:
  only:
    - master
    - develop

before_install:
  - env
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod repo update --silent
  - pod install --project-directory=Demo

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild clean -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" CODE_SIGNING_REQUIRED=NO | xcpretty -c

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      travis_retry xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

notifications:
  email: # false
    recipients:
      - fuxianchao2009@163.com
    on_success: always
    on_failure: always  

after_success:
  # - bash <(curl -s https://codecov.io/bash)
  - sleep 5










