# frozen_string_literal: true

source "https://gems.ruby-china.com"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

group :development do
  gem "ruby-lsp", require: false
end

gem "pry"
gem "cocoapods", '>= 1.12.1'
