# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ZDToolKitDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZDToolKitDemo
  pod 'SDWebImage'
  pod 'YYWebImage', '~> 1.0'
  pod 'ZDToolKit', :path => '../'
  

  target 'ZDToolKitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZDToolKitDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name != 'ZDToolKit'
                #block内直接引用全局变量的警告
                config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = 'NO'
                #关闭`This block declaration is not a prototype,Insert ‘void'`警告
                config.build_settings['CLANG_WARN_STRICT_PROTOTYPES'] = 'NO'
            end
        end
    end
end
