platform :ios, "8.0"

target 'ZDToolKitDemo' do
  pod 'SDWebImage', '~> 3.8.2'
  pod 'YYWebImage', '~> 1.0'
  pod 'ZDToolKit', :path => '../'
end

#target :<#TargetName#>Tests, :exclusive => true do
  # pod 'Kiwi'
#end